import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Box, Typography, Container } from '@mui/material'




const Home: NextPage = () => {
  return (
    
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Box >
        <Container >
          <Box >
            <p>Respostas na semana</p>

          </Box>
          <Box>
            <p >Satisfação no ano</p>

            <div className='text-center'>
              <p>ds</p>
              <p>ds</p>
              <p>sd</p>
            </div>
          </Box>
        </Container>
      </Box>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
